-- Add all potentially missing columns to customers table
-- Based on fields sent from customersService.js addCustomer method

ALTER TABLE public.customers 
  ADD COLUMN IF NOT EXISTS id TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS company TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS tax_number TEXT,
  ADD COLUMN IF NOT EXISTS balance DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS total_orders INTEGER,
  ADD COLUMN IF NOT EXISTS total_spent DECIMAL(15, 2),
  ADD COLUMN IF NOT EXISTS first_purchase DATE,
  ADD COLUMN IF NOT EXISTS last_purchase DATE,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
